ECE297 Storage Server: storage.c File Reference
storage.c File Reference
This file contains the implementation of the storage server interface as specified in storage.h.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include "storage.h"
#include "utils.h"
#include <errno.h>
Functions
void * storage_connect (const char *hostname, const int port)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_auth (const char *username, const char *passwd, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_get (const char *table, const char *key, struct storage_record *record, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_set (const char *table, const char *key, struct storage_record *record, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_disconnect (void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
Variables
int authenticated = 0
const int LOGGING
Detailed Description
This file contains the implementation of the storage server interface as specified in storage.h.
Definition in file storage.c.
Function Documentation
int storage_auth (const char * username, const char * passwd, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Authenticate the client's connection to the server.
Definition at line 78 of file storage.c.
References generate_encrypted_password(), logger(), MAX_CMD_LEN, recvline(), and sendall().
void* storage_connect (const char * hostname, const int port)
This is just a minimal stub implementation. You should modify it according to your design.
Establish a connection to the server.
Definition at line 27 of file storage.c.
References logger().
int storage_disconnect (void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Close the connection to the server.
Definition at line 295 of file storage.c.
References logger(), and MAX_CMD_LEN.
int storage_get (const char * table, const char * key, struct storage_record * record, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Retrieve the value associated with a key in a table.
Definition at line 125 of file storage.c.
References logger(), MAX_CMD_LEN, recvline(), sendall(), and storage_record::value.
int storage_set (const char * table, const char * key, struct storage_record * record, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Store a key/value pair in a table.
Definition at line 207 of file storage.c.
References logger(), MAX_CMD_LEN, recvline(), sendall(), and storage_record::value.