ECE297 Storage Server: utils.c File Reference
utils.c File Reference
This file implements various utility functions that are can be used by the storage server and client library.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
#include "utils.h"
Functions
int sendall (const int sock, const char *buf, const size_t len)
Keep sending the contents of the buffer until complete.
int recvline (const int sock, char *buf, const size_t buflen)
Receive an entire line from a socket.
int process_config_line (char *line, struct config_params *params)
Parse and process a line in the config file.
int read_config (const char *config_file, struct config_params *params)
Read and load configuration parameters.
void logger (char *message, int logging, int is_server)
Generates a log message.
char * generate_encrypted_password (const char *passwd, const char *salt)
Generates an encrypted password string using salt CRYPT_SALT.
int checkreturnmessage (char *message)
int checkinvalidparam (const char *cmdline, int detectspace)
Variables
FILE * cfp
FILE * sfp
int counter1 = 0
int counter2 = 0
int counter3 = 0
int counter4 = 0
int counter5 = 0
Detailed Description
This file implements various utility functions that are can be used by the storage server and client library.
Definition in file utils.c.
Function Documentation
char* generate_encrypted_password (const char * passwd, const char * salt)
Generates an encrypted password string using salt CRYPT_SALT.
Parameters:
passwd Password before encryption.
salt Salt used to encrypt the password. If NULL default value DEFAULT_CRYPT_SALT is used.
Returns:
Returns encrypted password.
Definition at line 216 of file utils.c.
References DEFAULT_CRYPT_SALT.
Referenced by storage_auth().
void logger (char * message, int logger, int is_server)
Generates a log message.
Parameters:
file The output stream
message Message to log.
Definition at line 177 of file utils.c.
Referenced by handle_command(), main(), storage_auth(), storage_connect(), storage_disconnect(), storage_get(), and storage_set().
int read_config (const char * config_file, struct config_params * params)
Read and load configuration parameters.
Parameters:
config_file The name of the configuration file.
params The structure where config parameters are loaded.
Returns:
Return 0 on success, -1 otherwise.
Definition at line 144 of file utils.c.
References process_config_line().
Referenced by main().
int recvline (const int sock, char * buf, const size_t buflen)
Receive an entire line from a socket.
In order to avoid reading more than a line from the stream, this function only reads one byte at a time. This is very inefficient, and you are free to optimize it or implement your own function.
Definition at line 48 of file utils.c.
Referenced by main(), storage_auth(), storage_get(), and storage_set().
int sendall (const int sock, const char * buf, const size_t len)
Keep sending the contents of the buffer until complete.
Returns:
Return 0 on success, -1 otherwise.
The parameters mimic the send() function.
Definition at line 28 of file utils.c.
Referenced by handle_command(), storage_auth(), storage_get(), and storage_set().