ECE297 Storage Server: utils.h File Reference
utils.h File Reference
This file declares various utility functions that are can be used by the storage server and client library.
#include <stdio.h>
#include "storage.h"
Classes
struct config_params
A struct to store config parameters.
Defines
#define MAX_CMD_LEN (1024 * 8)
The max length in bytes of a command from the client to the server.
#define LOG(x) {printf x; fflush(stdout);}
A macro to log some information.
#define DBG(x) {printf x; fflush(stdout);}
A macro to output debug information.
#define DEFAULT_CRYPT_SALT "xx"
Default two character salt used for password encryption.
Functions
int sendall (const int sock, const char *buf, const size_t len)
Keep sending the contents of the buffer until complete.
int recvline (const int sock, char *buf, const size_t buflen)
Receive an entire line from a socket.
int read_config (const char *config_file, struct config_params *params)
Read and load configuration parameters.
void logger (char *message, int logger, int is_server)
Generates a log message.
char * generate_encrypted_password (const char *passwd, const char *salt)
Generates an encrypted password string using salt CRYPT_SALT.
int checkreturnmessage (char *message)
int checkinvalidparam (const char *cmdline, int detectspace)
Variables
FILE * cfp
FILE * sfp
Detailed Description
This file declares various utility functions that are can be used by the storage server and client library.
Definition in file utils.h.
Define Documentation
#define DBG (x) {printf x; fflush(stdout);}
A macro to output debug information.
It is only enabled in debug builds.
Definition at line 41 of file utils.h.
#define LOG (x) {printf x; fflush(stdout);}
A macro to log some information.
Use it like this: LOG(("Hello %s", "world\n"))
Don't forget the double parentheses, or you'll get weird errors!
Definition at line 31 of file utils.h.
Referenced by handle_command(), and main().
Function Documentation
char* generate_encrypted_password (const char * passwd, const char * salt)
Generates an encrypted password string using salt CRYPT_SALT.
Parameters:
passwd Password before encryption.
salt Salt used to encrypt the password. If NULL default value DEFAULT_CRYPT_SALT is used.
Returns:
Returns encrypted password.
Definition at line 216 of file utils.c.
References DEFAULT_CRYPT_SALT.
Referenced by storage_auth().
void logger (char * message, int logger, int is_server)
Generates a log message.
Parameters:
file The output stream
message Message to log.
Definition at line 177 of file utils.c.
Referenced by handle_command(), main(), storage_auth(), storage_connect(), storage_disconnect(), storage_get(), and storage_set().
int read_config (const char * config_file, struct config_params * params)
Read and load configuration parameters.
Parameters:
config_file The name of the configuration file.
params The structure where config parameters are loaded.
Returns:
Return 0 on success, -1 otherwise.
Definition at line 144 of file utils.c.
References process_config_line().
Referenced by main().
int recvline (const int sock, char * buf, const size_t buflen)
Receive an entire line from a socket.
Returns:
Return 0 on success, -1 otherwise.
In order to avoid reading more than a line from the stream, this function only reads one byte at a time. This is very inefficient, and you are free to optimize it or implement your own function.
Definition at line 48 of file utils.c.
Referenced by main(), storage_auth(), storage_get(), and storage_set().
int sendall (const int sock, const char * buf, const size_t len)
Keep sending the contents of the buffer until complete.
Returns:
Return 0 on success, -1 otherwise.
The parameters mimic the send() function.
Definition at line 28 of file utils.c.
Referenced by handle_command(), storage_auth(), storage_get(), and storage_set().